### ISSUE TITLE
Pick a payment gateway solution after some R & D on available options

### ISSUE THREAD

**Issue by omeryousaf** [omeryousaf/website-with-payment-gateway#1]
## Description
We want to compile data on pros (power / flexibility etc) and cons (limitations) of the payment gateway solutions that are available in order to pick and try some of them for a regular online business.

## Acceptance Criteria
A list of payment processing solutions with their ratings / powerful features / ease of use / limitations etc. to help in picking one from them to try out.

**Comment by omeryousaf** [comment]
@Shapokhan added this as the first story to this project. Feel free to upload any findings u have on the solutions u have come across.

**Comment by Shapokhan** [comment]
After some research, we have decided to implement a jazz cash payment gateway in our project.
